list1 = set(map(int, input("첫 번째 리스트를 입력하세요: ").split(",")))
list2 = set(map(int, input("두 번째 리스트를 입력하세요: ").split(",")))
print(f"교집합: {list1 & list2}")
print(f"합집합: {list1 | list2}")
print(f"차집합: {list1 - list2}")